### ISSUE TITLE
Malformed version number string 1.2-devel

### ISSUE THREAD

**Issue by n-rodriguez** [oliverguenther/gitolite-rugged#2]
Hi Oliver!

It seems that the version number is not well handled by the `gem` command

```
redmine@fs2 ~/redmine % bundle install 
Updating git://github.com/n-rodriguez/gitolite-rugged.git
There was a ArgumentError while loading gitolite.gemspec: 
Malformed version number string 1.2-devel from /opt/redmine/.bundler/ruby/1.9.1/gitolite-rugged-0a45149bdd2d/gitolite.gemspec:7:in `block in <main>'
```

https://github.com/jbox-web/redmine_git_hosting/issues/229

**Comment by oliverguenther** [comment]
Weird. The gemspec allows any letter in the version to set determine the gem as a prerelease. Maybe bundle dislikes that practice. I'll stick to pre/regular versions in the next release.

**Comment by ataraxus** [comment]
i stumbled upon the same problem with release 8.0. what is the solution? 
Sorry but i'm quite new to ruby...
